# The name of the project (required) is used for display purposes within IO environments and IDEs.
name: ads_flutter
# A list of paths to local packages that are included in the Melos workspace. Each entry can be a specific path or a glob pattern.
packages:
  - "apps/*"
  - "libraries/**"


scripts:
  analyze:
    exec: dart analyze .