name: go_router_export
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.1.0
  build_runner: ^2.1.0

