name: commons
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  go_router: ^14.3.0
  equatable: ^2.0.5
  material_design_icons_flutter: ^7.0.7296

  cubit_export:
    path: lib/cubit_export

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.1.0
  build_runner: ^2.1.0

