name: feature_flag
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_manager:
    path: ../firebase_manager
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
