name: secure_storage
description: "Package contains a Shared Prefences and Secure Storage"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  get_it_export:
    path: ../../services/commons/dependencies/get_it
  injectable_export:
    path: ../../services/commons/dependencies/injectable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.0
  injectable_generator: ^2.1.0

