name: core
description: "A new Flutter module project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio_export:
    path: ../services/commons/dependencies/dio
  go_router_export:
    path: ../services/commons/dependencies/go_router
  get_it_export:
    path: ../services/commons/dependencies/get_it
  injectable_export:
    path: ../services/commons/dependencies/injectable
  feature_flag:
    path: ../services/feature_flag
  firebase_manager:
    path: ../services/firebase_manager
  material_design_icons_export:
    path: ../services/commons/dependencies/material_design_icons
  equatable_export:
    path: ../services/commons/dependencies/equatable
  secure_storage:
    path: ../services/secure_storage
  

  home:
    path: ../libraries/home
  landing:
    path: ../libraries/landing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.0
  injectable_generator: ^2.1.0
  

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.core
    iosBundleIdentifier: com.example.core
