name: Dart Monorepo with Melos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Set up Melos
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Install dependencies (Melos)
        run: melos bootstrap

      - name: Run Flutter Lint (Melos)
        run: melos run analyze
        continue-on-error: false

      - name: Run tests (Melos)
        run: melos run test
        continue-on-error: true
